### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### create student
POST http://localhost:9000/api/v1/students
Content-Type: application/json

{
  "firstName": "juan",
  "lastName": "test",
  "dateOfBirth": "2020-05-10",
  "studentCode": "A1"
}

### updated student
PUT http://localhost:9000/api/v1/students/1
Content-Type: application/json

{
  "firstName": "Felipe",
  "lastName": "Cardona",
  "dateOfBirth": "2000-05-10",
  "studentCode": "A3"
}

### get students
GET http://localhost:9000/api/v1/students

### get student projection
GET http://localhost:9000/api/v1/students/projection/A3

### delete student by Id
DELETE http://localhost:9000/api/v1/students/1